// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetUser(arg1:number):Promise<backend.User>;

export function Hello(arg1:string):Promise<string>;
