// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUser(arg1) {
  return window['go']['backend']['API']['GetUser'](arg1);
}

export function Hello(arg1) {
  return window['go']['backend']['API']['Hello'](arg1);
}
