// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetUser(arg1:number):Promise<models.User>;

export function Hello(arg1:string):Promise<string>;

export function ListUsers():Promise<Array<models.User>>;
