name: Build OSBB App (windows/amd64)

on:
  push:
    branches: [ main ]
  workflow_dispatch: ###

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Wails CLI
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build Wails App
      run: wails build -platform windows/amd64 --nsis -o osbb.exe

    - name: Build Windows Installer
      run: makensis /DARG_WAILS_AMD64_BINARY="build/bin/osbb.exe" build/windows/installer/project.nsi

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: osbb-windows
        path: build/bin/osbb.exe
