name: Build OSBB App (windows/amd64)

on:
  push:
    branches: [ master ]
  workflow_dispatch: ###

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Wails CLI
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build Wails App
      run: wails build -platform windows/amd64 --output build/window/osbb_amd64.exe

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: osbb-windows-build
        path: build/windows/osbb_amd64.exe
